### ISSUE TITLE
Pressing undo button after starting game causes timer glitch

### ISSUE THREAD

**Issue by jinanparves** [HuskieRobotics/SPOT#100]
If you continuously press the undo and start button, one after the other, the timer starts to glitch out. It seems that there is an overlay between the auto timer and the teleop timer.

**Comment by jinanparves** [comment]
Also, pressing undo with no inputs AFTER autos has ended will cause SPOT to go into the autos interface again.

**Comment by gcschmit** [comment]
match-scouting.js starting at line 71 may be relevant

**Comment by ACoderGuy1002** [comment]
> match-scouting.js starting at line 71 may be relevant

I fixed it by doing this:
![fix](https://github.com/user-attachments/assets/cc2bf705-db9c-4515-8c96-6fddd7b5edc7)

**Comment by ACoderGuy1002** [comment]
> > match-scouting.js starting at line 71 may be relevant
> 
> I fixed it by doing this: ![fix](https://private-user-images.githubusercontent.com/94772285/382440350-cc2bf705-db9c-4515-8c96-6fddd7b5edc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTczMzcsIm5iZiI6MTczMDUxNzAzNywicGF0aCI6Ii85NDc3MjI4NS8zODI0NDAzNTAtY2MyYmY3MDUtZGI5Yy00NTE1LThjOTYtNmZkZGQ3YjVlZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDAzMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Mzg4NzU1M2QwNGEyZDI1ZWM5Nzk5MzdiNzlmNWE2NmY2YWQyYjRjYzAyM2Y0YTJhYTVkNDFiZTYxZGFmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3vMIHx6gDc_EfQ8a-rkGqP9HLlA1fqaFcATl_NwT-fU)

Change 1 to 2
