### ISSUE TITLE
after dismissing the QR code page, redirect to the landing page

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/SPOT#125]
Currently, when the QR code page is dismissed, you remain on the scouting page. You should be redirected to the landing page.

**Comment by Yashaswi0413** [comment]
hey @gcschmit i'm looking forward to solve the bug. i'm facing issue in the setup of the project. i couldn't right place to get TBA api key. can u help me with it?

**Comment by gcschmit** [comment]
@Yashaswi0413 Thank you so much for your offer! This issue should have been closed when PR #127 was accepted. I'll do that now.

Regardless, to answer your question, create an account on the The Blue Alliance web site if you haven't already. Then you can go to [your account page](https://www.thebluealliance.com/account) and request an API key.

**Comment by Yashaswi0413** [comment]
@gcschmit Got it, thank you for the answer.
