### ISSUE TITLE
Cannot connect on remote devices and how to use without internet access

### ISSUE THREAD

**Issue by orondemanson** [HuskieRobotics/SPOT#58]
How can I use this without wifi or a cell hotspot because that is not allowed at the competitions? Also, how can I connect to it on a remote device not on the local host? (ie a tablet, which ip to connect to) and how would it get the actual match data?

**Comment by nithilan4** [comment]
Full offline is coming soon (includes analysis and a limited admin view), but for now, you just have to load the page beforehand when you have internet and add it to the home screen as an app when it prompts you to, and it should load even when offline after that.

As far as another device, you will have to host it somewhere for every device to be able to access through the internet. The quickstart guide for setting it up on glitch is quick and easy, and you'll be able to have it hosted for free with some minor limitations.
