### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by AtomicPainter40** [HuskieRobotics/SPOT#88]
I have everything set up including the server, API key, etc. But when I reloaded the website, it's showing that it's not connected. It's connected to the internet, but it won't connect to the server. MongoDB is showing it has active connections so I don't have any clue on why it's not connecting.
![image](https://github.com/HuskieRobotics/SPOT/assets/85978052/f8f51cf1-b8ec-4412-9511-044ed315461d)
![image](https://github.com/HuskieRobotics/SPOT/assets/85978052/94b8ee67-7274-4107-b001-ba2f6bed9211)

**Comment by gcschmit** [comment]
@AtomicPainter40 It appears that you were able to resolve the issue, which is great. How did you fix it? I expect that clarifying something in our documentation would make it easier for others. Thanks!
